import React from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const posts = [
  {
    title: "Поради для ідеального весільного фото",
    description: "Дізнайтесь, як зробити день весілля незабутнім на фотографіях.",
    image: "/blog/wedding-tips.jpg",
    slug: "post-1",
  },
  {
    title: "Як вибрати природне світло",
    description: "Поради для портретної зйомки з натуральним освітленням.",
    image: "/blog/natural-light.jpg",
    slug: "post-2",
  },
  {
    title: "Сімейна фотосесія: як підготуватись",
    description: "Гід для сімей, які хочуть зберегти теплі моменти.",
    image: "/blog/family-guide.jpg",
    slug: "post-3",
  },
];

const BlogSection = () => (
  <section className="py-10 px-4 md:px-12 lg:px-24" id="blog">
    <h2 className="text-3xl font-bold mb-6">Блог</h2>
    <div className="grid gap-6 md:grid-cols-3">
      {posts.map(({ title, description, image, slug }) => (
        <Card key={slug} className="overflow-hidden">
          <img src={image} alt={title} className="w-full h-48 object-cover" />
          <CardContent className="p-4">
            <h3 className="text-xl font-semibold mb-2">{title}</h3>
            <p className="text-gray-600 mb-4">{description}</p>
            <Button variant="outline" asChild>
              <a href={`/blog/${slug}.html`} target="_blank" rel="noopener noreferrer">
                Читати далі
              </a>
            </Button>
          </CardContent>
        </Card>
      ))}
    </div>
  </section>
);

export default BlogSection;
